name: goodimg-parallelreq

on:
  workflow_dispatch:  # Execute manually only
permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  run-ADE-tier3:
    name: Run GOODIMG AGDE Tier 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execution permissions
        run: chmod +x goodimg-parallelreq/ag-de/GA-stg-tier3-run-agde.sh

      - name: Run ADE Tier 3 script
        run: ./goodimg-parallelreq/ag-de/GA-stg-tier3-run-agde.sh

      - name: Show content of the T3 log.
        run: cat goodimg-parallelreq/reports/ADE-T3_goodimg_report.txt || echo "❌ The file does not exist or is empty"

      - name: Upload ADE-T3_goodimg_report
        uses: actions/upload-artifact@v4
        with:
          name: request-log-ADE-tier3
          path: goodimg-parallelreq/reports/ADE-T3_goodimg_report.txt

  run-AOD-tier3:
    name: Run GOODIMG AOD Tier 3
    runs-on: ubuntu-latest
    needs: run-ADE-tier3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execution permissions
        run: chmod +x goodimg-parallelreq/ag-od/GA-stg-tier3-run-agod.sh

      - name: Run AOD Tier 3 script
        run: ./goodimg-parallelreq/ag-od/GA-stg-tier3-run-agod.sh

      - name: Show content of the T3 log.
        run: cat goodimg-parallelreq/reports/AOD-T3_goodimg_report.txt || echo "❌ The file does not exist or is empty"

      - name: Upload AOD-T3_goodimg_report
        uses: actions/upload-artifact@v4
        with:
          name: request-log-AOD-tier3
          path: goodimg-parallelreq/reports/AOD-T3_goodimg_report.txt
