name: Test Artifact Upload

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy file
        run: echo "Hello from test" > test-log.txt

      - name: Upload dummy file
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-log
          path: test-log.txt
