name: run-rate-limit-tests

on:
  workflow_dispatch:  # Esto hace que el workflow se ejecute solo manualmente

jobs:
  run-rate-limit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x Rate-Limit/run-agde-tier1.sh

      - name: Run rate-limit test script
        run: ./Rate-Limit/run-agde-tier1.sh

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: request-log
          path: Rate-Limit/request_log.txt  # Asegúrate de que el archivo esté en esa ruta

