name: PROD-zero-credits

on:
  workflow_dispatch: 

jobs:
  PROD-API-Run-Zero-Credits: 
    name: PROD-API-zero-credits
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests
      
    - name: Run zero-credits API script
      run: python zero-credits/PROD/PROD-API-zero-credits.py
   